let number1 = Math.floor((Math.random() * (99 - 10 + 1)) + 10);
let number2 = Math.floor((Math.random() * (99 - 10 + 1)) + 10);
let number3 = Math.floor((Math.random() * (99 - 10 + 1)) + 10);
let number4 = Math.floor((Math.random() * (99 - 10 + 1)) + 10);
let number5 = Math.floor((Math.random() * (99 - 10 + 1)) + 10);
console.log(number1);
console.log(number2);
console.log(number3);
console.log(number4);
console.log(number5);
let sum = number1 + number2 + number3 + number4 + number5;
console.log("sum = " + sum);
let average = sum / 5;
console.log("Avg = " + average);